# The URL the site will be built for
base_url = "https://blog.glowatski.com"
name = "bebop-blog"
description = "A blog about stuff I write about"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

taxonomies = [{ name = "tags" }]

default_language = "en"

theme="archie-zola"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

highlight_theme = "OneHalfDark"

[author]
name = "Brandon"

[extra]
# Put all your custom variables here
# control dark mode: auto | dark | toggle
mode = "auto"

# subtitle will show under the title in index page
subtitle = "See ya later space cowboy"

# if set true, will use external CDN resource to load font and js file
useCDN = false

favicon = "/images/128.png"

# show in the footer
copyright = "Brandon Glowatski"

# optional: config your i18n entry
[extra.translations]
languages = [{name = "en", url = "/"}]

# config multi-language menu and other text
[[extra.translations.en]]
show_more = "Read more ⟶"
previous_page = "← Previous"
next_page = "Next →"
posted_on = "on "
posted_by = "Published by"
read_time = "minute read"
all_tags = "All tags"
menus = [
    { name = "Home", url = "/", weight = 2 },
    { name = "Posts", url = "/posts", weight = 2 },
    { name = "About", url = "/about", weight = 3 },
    { name = "Tags", url = "/tags", weight = 4 },
]

# config social icon info in the footer
[[extra.social]]
icon = "github"
name = "GitHub"
url = "https://github.com/glowatsk"

